project:
  type: website

website:
  title: "ISSS626-QiuYan"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1a"
            href: "Hands-on_Ex/Hands-on_Ex01/chap01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 1b"
            href: "Hands-on_Ex/Hands-on_Ex01/chap02/Hands-on_Ex01b.html"
            


      - text: "In-Class Exercise"
        menu:
          - text: "In-Class Exercise 1"
            href: " "

            
            
      - text: "Take Home Exercise"
        menu:
          - text: "Take Home Exercise 1"
            href: "TakeHome_Ex/TakeHome_Ex01/TakeHome_Ex01.html"
            

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual