---
title: "Take home exercise 1"
author: "Tai Qiu Yan"
date: "September 12, 2025"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

##Loading the R packages

```{r}
pacman::p_load(tidyverse, sf, tmap, httr)
```

## Importing ACRA data

```{r}
folder_path <- "data/aspatial/acra"
file_list <- list.files(path = folder_path,
                        pattern = "^ACRA*.*\\.csv$",
                        full.names = TRUE)

acra_data <- file_list %>%
  map_dfr(read_csv)
```

## Saving ACRA data

```{r}
write_rds(acra_data,
          "data/rds/acra_data.rds")
```

## Tidying ACRA data

56111 is the type of business selected.

```{r}
biz_56111 <- acra_data %>%
  select(1:24) %>%
  filter(primary_ssic_code == 56111) %>%
  rename(date = registration_incorporation_date) %>%
  mutate(date = as.Date(date),
         YEAR = year(date),
         MONTH_NUM = month(date),
         MONTH_ABBR = month(date,
                            label = TRUE,
                            abbr = TRUE)) %>%
  mutate(
    postal_code = str_pad(postal_code, 
    width = 6, side = "left", pad = "0")) %>% 
           filter(YEAR == 2025)
```

## Geocoding

found: successfully geocoded
not found: unsuccessfully geocoded


