---
title: "In-class_Ex08a"
author: "Tai Qiu Yan"
date: "October 25, 2025"
date-modified: "last-modified"
format: html
editor: visual
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

# In class Ex 8a

```{r}
pacman::p_load(httr, tidyverse, sf, tmap, jsonlite, progress)
```

## Geocoding HDB resale data

### Basic Version

```{r}
HDBresale <- read_csv(
  "data/rawdata/HDBresale.csv") %>%
  filter(flat_type == "4 ROOM") %>%
  filter(month >= "2025-09" & month < "2025-10")
```

```{r}
HDBresale$street_name <- gsub(
  "ST\\.", "SAINT",
  HDBresale$street_name)
```

```{r}
geocode <- function(block, streetname) {
  base_url <- "https://onemap.gov.sg/api/common/elastic/search"
  address <- paste(block, streetname, sep = " ")
  query <- list(
    "searchVal" = address,
    "returnGeom" = "Y",
    "getAddrDetails" = "N",
    "pageNum" = "1")

  res <- GET(base_url, query = query)
  restext <- content(res, as = "text")

  output <- fromJSON(restext) %>%
    as.data.frame %>%
    select(results.LATITUDE, results.LONGITUDE)

  return(output)
}
```

```{r}
HDBresale$LATITUDE <- 0
HDBresale$LONGITUDE <- 0

for (i in 1:nrow(HDBresale)) {
  temp_output <- geocode(HDBresale[i, 4], HDBresale[i, 5])
  
  HDBresale$LATITUDE[i]  <- temp_output$results.LATITUDE
  HDBresale$LONGITUDE[i] <- temp_output$results.LONGITUDE
}
```

```{r}
HDBresale_sf <- HDBresale %>%
  st_as_sf(
    coords = c("LONGITUDE", "LATITUDE"), 
    crs = 4326) %>%
  st_transform(crs = 3414)
```

```{r}
preschool <- st_read("data/rawdata/PreSchoolsLocation.kml") %>% 
  st_transform(crs = 3414)
```

```{r}
within_350m <- st_is_within_distance(
  HDBresale_sf, preschool, dist = 350)

HDBresale_sf <- HDBresale_sf %>%
  mutate(prischool_350m = map_int(within_350m, length))
```

# In class Ex 8b

```{r}
pacman::p_load(
  sf, spdep, GWmodel, SpatialML,
  tmap, rsample, Metrics, tidyverse,
  knitr, kableExtra, spatialRF,
  randomForestExplainer)
```

```{r}
mdata <- read_rds("data/rawdata/mdata.rds")
```

```{r}
set.seed(1234)

HDB_sample <- mdata %>%
  sample_n(1500)
```

```{r}
HDB_sample <- HDB_sample %>%
  st_jitter(amount = 1)
```

```{r}
set.seed(1234)
resale_split <- initial_split(HDB_sample, 
                              prop = 6.67/10)

train_data <- training(resale_split)
test_data  <- testing(resale_split)
```
